### PR TITLE
chore(tests): Avoid mocking internal compiler state to test phase actions

### PR DESCRIPTION
**Pull request by Johnnei**
Rewire ScapegoatPhaseTest to run Dotty instead of trying to mock the internal state of the compiler well enough to be able to test it directly. This will fix the errors caused by upgrading to 3.6.2 in #904

### CODE REVIEW

**Comment by Johnnei** [comment]
@saeltz Please help review this one. I've tested it locally with 3.6.2 but didn't include that part to keep the change isolated.

**Comment by saeltz** [comment]
Would you please revert the unrelated formatting changes in the inspection file?

**Comment by Johnnei** [comment]
> Would you please revert the unrelated formatting changes in the inspection file?

Done. Probably worth to add `scalafmtCheck` into the additional checks job as that file got reformatted from an scalafmtAll to clean up my change.

**Review by saeltz — APPROVED** [review]

**Comment by saeltz** [comment]
Thanks! Created #911.

**Pull request merged**
