### PR TITLE
Add support for scala 2.13.10

### PR DESCRIPTION
**Pull request by henricook**
We're thinking about removing our scapegoat dependency because in a scala version upgrade it's the only dependency (in our project with many dependencies) that doesn't seem to "just work". Do you think there's a better strategy that could be employed instead of manually naming versions like this?

### CODE REVIEW

**Comment by henricook** [comment]
@saeltz  @mccartney If it's not too forward to tag you both - I'd appreciate a review when you get a moment, very similar to my 2.13.9 MR of last week

**Review by mccartney — APPROVED** [review]

**Comment by mccartney** [comment]
The failed check is scoverage failure which doesn't seem to have a version for 2.13.10 (?) or not sure what the problem with it is.

**Comment by mccartney** [comment]
>  scala version upgrade it's the only dependency (in our project with many dependencies) that doesn't seem to "just work".

Not sure what are you suggesting. Is it about not having a separate version of scapegoat per Scala **minor** version?

**Comment by henricook** [comment]
Thanks for release!

I'm not sure, do all our other dependencies just react very very fast (or automatically?). I'm not sure of the intricacies - I might have to look around to see how it's done

**Pull request merged**
