### PR TITLE
Scala 2.13.12

### LINKED ISSUE #780: Scala 2.13.12
https://github.com/scala/scala/releases/tag/v2.13.12 is out. We need a build for this.

### PR DESCRIPTION
**Pull request by mccartney**
Fixes #780

### CODE REVIEW

**Review by saeltz — APPROVED** [review]

**Comment by mccartney** [comment]
At least one more problem to solve. It looks like they have changed the interface of the (internal) `StoreReporter.Info`. Unless we find some trick/workaround, we would need to have some conditional code based on Scala minor version (that'd be something to avoid).

**Comment by saeltz** [comment]
This would work:
```
        reporter.infos.head should matchPattern {
          case info: StoreReporter.Info
              if info.pos == position && info.msg.contains(
                "[scapegoat] [DummyInspection] My default is Error\n  This is explanation."
              ) && info.severity == reporter.ERROR =>
```

**Comment by mccartney** [comment]
No time to check it out right now. Feel free to push to this branch.

**Comment by SethTisue** [comment]
superseded by #789, looks like

**Pull request closed without merging**
